### PR TITLE
Correct linkify

### LINKED ISSUE #490: Editor: incorrect autolink behavior
ref: https://github.com/thematters/matters-editor/issues/449

### PR DESCRIPTION
**Pull request by robertu7**
* resolve #490 [0]
* sync with latest https://github.com/ueberdosis/tiptap/blob/main/packages/extension-link/src/link.ts;

[0] https://github.com/thematters/matters-editor/pull/488/files#diff-e3154d2e1804afbd6b52743af561334d6f40462ac5e294108f994d3c4c4e48deR286-R290

### CODE REVIEW

File: src/editors/extensions/link/helpers/autolink.ts [hunk 1]
```diff
@@ -3,78 +3,79 @@ import {
...
+
+  if (tokens.length === 3 && tokens[1].isLink) {
+    return ['()', '[]'].includes(tokens[0].value + tokens[2].value)
+  }
+
+  return false
+}
 
-interface AutolinkOptions {
+type AutolinkOptions = {
```
Comment (byhow) [inline src/editors/extensions/link/helpers/autolink.ts:36]: nice

**Review by byhow — APPROVED** [review]
LGTM
